manifest:
  defaults:
    revision: v0.3
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: harryzmk
      url-base: https://github.com/harrygao56/zmk
  projects:
    - name: zmk
      remote: harryzmk
      import: app/west.yml
  self:
    path: config
